
import {
  IoPhonePortraitOutline,
  IoShirtOutline,
  IoHomeOutline,
  IoFlowerOutline,
  IoFootballOutline,
  IoColorPaletteOutline,
  IoBookOutline,
  IoBicycleOutline,
  IoFastFoodOutline,
  IoLeafOutline,
  IoPawOutline,
  IoCarOutline,
  IoMusicalNotesOutline,
  IoGameControllerOutline,
  IoWatchOutline,
  IoBagOutline,
  IoHeartOutline,
  IoCameraOutline,
  IoConstructOutline,
  IoAirplaneOutline,
  IoPencilOutline,
  IoStarOutline,
} from "react-icons/io5";
import { HiTrendingUp } from "react-icons/hi";
import { LuBaby } from "react-icons/lu";

export const ALL_CATEGORIES = [
  {
    id: 1,
    name: "Electronics",
    icon: <IoPhonePortraitOutline size={20} />,
    iconBg: "bg-violet-100 text-violet-600",
    description: "Devices, gadgets and electronic accessories",
    products: 548,
    status: "Active",
    performance: "Best Seller",
  },
  {
    id: 2,
    name: "Fashion",
    icon: <IoShirtOutline size={20} />,
    iconBg: "bg-emerald-100 text-emerald-600",
    description: "Men, women and kids clothing and accessories",
    products: 892,
    status: "Active",
    performance: "High Performer",
  },
  {
    id: 3,
    name: "Home & Kitchen",
    icon: <IoHomeOutline size={20} />,
    iconBg: "bg-orange-100 text-orange-500",
    description: "Home appliances, kitchen tools and essentials",
    products: 365,
    status: "Active",
    performance: "Average",
  },
  {
    id: 4,
    name: "Beauty & Personal Care",
    icon: <IoFlowerOutline size={20} />,
    iconBg: "bg-pink-100 text-pink-500",
    description: "Skincare, haircare, makeup and personal care",
    products: 287,
    status: "Active",
    performance: "High Performer",
  },
  {
    id: 5,
    name: "Sports & Outdoors",
    icon: <IoFootballOutline size={20} />,
    iconBg: "bg-sky-100 text-sky-500",
    description: "Fitness equipment, sports gear and outdoor essentials",
    products: 234,
    status: "Active",
    performance: "Average",
  },
  {
    id: 6,
    name: "Home Decor",
    icon: <IoColorPaletteOutline size={20} />,
    iconBg: "bg-amber-100 text-amber-500",
    description: "Decorative items, wall art, lights and more",
    products: 12,
    status: "Inactive",
    performance: "Underperforming",
  },
  {
    id: 7,
    name: "Books & Stationery",
    icon: <IoBookOutline size={20} />,
    iconBg: "bg-indigo-100 text-indigo-500",
    description: "Books, notebooks, pens and office supplies",
    products: 410,
    status: "Active",
    performance: "Average",
  },
  {
    id: 8,
    name: "Bicycles & Cycling",
    icon: <IoBicycleOutline size={20} />,
    iconBg: "bg-lime-100 text-lime-600",
    description: "Cycles, helmets, accessories and gear",
    products: 89,
    status: "Active",
    performance: "Average",
  },
  {
    id: 9,
    name: "Food & Grocery",
    icon: <IoFastFoodOutline size={20} />,
    iconBg: "bg-yellow-100 text-yellow-600",
    description: "Packaged foods, fresh produce and pantry staples",
    products: 672,
    status: "Active",
    performance: "High Performer",
  },
  {
    id: 10,
    name: "Organic & Natural",
    icon: <IoLeafOutline size={20} />,
    iconBg: "bg-green-100 text-green-600",
    description: "Organic food, natural skincare and eco products",
    products: 143,
    status: "Active",
    performance: "Average",
  },
  {
    id: 11,
    name: "Pet Supplies",
    icon: <IoPawOutline size={20} />,
    iconBg: "bg-orange-100 text-orange-600",
    description: "Food, toys and accessories for pets",
    products: 198,
    status: "Active",
    performance: "Average",
  },
  {
    id: 12,
    name: "Automotive",
    icon: <IoCarOutline size={20} />,
    iconBg: "bg-slate-100 text-slate-600",
    description: "Car accessories, tools and spare parts",
    products: 77,
    status: "Inactive",
    performance: "Underperforming",
  },
  {
    id: 13,
    name: "Musical Instruments",
    icon: <IoMusicalNotesOutline size={20} />,
    iconBg: "bg-fuchsia-100 text-fuchsia-600",
    description: "Guitars, keyboards, percussion and accessories",
    products: 54,
    status: "Active",
    performance: "Average",
  },
  {
    id: 14,
    name: "Gaming",
    icon: <IoGameControllerOutline size={20} />,
    iconBg: "bg-violet-100 text-violet-700",
    description: "Consoles, games, controllers and gaming gear",
    products: 321,
    status: "Active",
    performance: "High Performer",
  },
  {
    id: 15,
    name: "Watches & Wearables",
    icon: <IoWatchOutline size={20} />,
    iconBg: "bg-rose-100 text-rose-500",
    description: "Smartwatches, fitness bands and luxury timepieces",
    products: 163,
    status: "Active",
    performance: "Average",
  },
  {
    id: 16,
    name: "Bags & Luggage",
    icon: <IoBagOutline size={20} />,
    iconBg: "bg-teal-100 text-teal-600",
    description: "Backpacks, travel bags, wallets and accessories",
    products: 209,
    status: "Active",
    performance: "Average",
  },
  {
    id: 17,
    name: "Health & Wellness",
    icon: <IoHeartOutline size={20} />,
    iconBg: "bg-red-100 text-red-500",
    description: "Supplements, medical devices and wellness products",
    products: 335,
    status: "Active",
    performance: "High Performer",
  },
  {
    id: 18,
    name: "Cameras & Photography",
    icon: <IoCameraOutline size={20} />,
    iconBg: "bg-blue-100 text-blue-600",
    description: "Cameras, lenses, tripods and photography accessories",
    products: 118,
    status: "Active",
    performance: "Average",
  },
  {
    id: 19,
    name: "Tools & Hardware",
    icon: <IoConstructOutline size={20} />,
    iconBg: "bg-zinc-100 text-zinc-600",
    description: "Power tools, hand tools and workshop accessories",
    products: 44,
    status: "Inactive",
    performance: "Underperforming",
  },
  {
    id: 20,
    name: "Travel Accessories",
    icon: <IoAirplaneOutline size={20} />,
    iconBg: "bg-cyan-100 text-cyan-600",
    description: "Travel pillows, adapters, organizers and gear",
    products: 96,
    status: "Active",
    performance: "Average",
  },
  {
    id: 21,
    name: "Baby & Kids",
    icon: <LuBaby size={20} />,
    iconBg: "bg-pink-100 text-pink-400",
    description: "Toys, clothing, nursery and baby essentials",
    products: 274,
    status: "Active",
    performance: "High Performer",
  },
  {
    id: 22,
    name: "Art & Craft",
    icon: <IoPencilOutline size={20} />,
    iconBg: "bg-yellow-100 text-yellow-500",
    description: "Craft supplies, painting materials and DIY kits",
    products: 61,
    status: "Active",
    performance: "Average",
  },
  {
    id: 23,
    name: "Star Picks",
    icon: <IoStarOutline size={20} />,
    iconBg: "bg-amber-100 text-amber-600",
    description: "Editor's choice and highly rated products",
    products: 30,
    status: "Active",
    performance: "Average",
  },
  {
    id: 24,
    name: "Trending Now",
    icon: <HiTrendingUp size={20} className="" />,
    iconBg: "bg-emerald-100 text-emerald-600",
    description: "Fast-moving and viral products across categories",
    products: 512,
    status: "Active",
    performance: "Best Seller",
  },
];

export const ROWS_PER_PAGE = 6;

export const STATUS_OPTIONS = ["All Status", "Active", "Inactive"];

export const PERFORMANCE_OPTIONS = [
  "All Performance",
  "Best Seller",
  "High Performer",
  "Average",
  "Underperforming",
];