import { HiTrendingUp } from "react-icons/hi";
import { TbPackageOff, TbAlertTriangleFilled } from "react-icons/tb";

export const ALL_PRODUCTS = [
  {
    id: 1,
    sku: "SW-001",
    name: "Smart Watch Series 9",
    category: "Electronics",
    price: 299.99,
    stock: 45,
    status: "Trending",
  },
  {
    id: 2,
    sku: "WH-002",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 199.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 3,
    sku: "CM-003",
    name: "Coffee Maker Pro",
    category: "Home & Kitchen",
    price: 89.99,
    stock: 5,
    status: "Low Stock",
  },
  {
    id: 4,
    sku: "YM-004",
    name: "Premium Yoga Mat",
    category: "Sports & Fitness",
    price: 39.99,
    stock: 23,
    status: "In Stock",
  },
  {
    id: 5,
    sku: "DC-005",
    name: "Digital Camera 4K",
    category: "Electronics",
    price: 599.99,
    stock: 12,
    status: "Low Stock",
  },
  {
    id: 6,
    sku: "RS-006",
    name: "Running Shoes Pro",
    category: "Sports & Fitness",
    price: 129.99,
    stock: 38,
    status: "In Stock",
  },
  {
    id: 7,
    sku: "BL-007",
    name: "Blender 1200W",
    category: "Home & Kitchen",
    price: 74.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 8,
    sku: "LT-008",
    name: "Laptop Stand Adjustable",
    category: "Electronics",
    price: 49.99,
    stock: 67,
    status: "In Stock",
  },
  {
    id: 9,
    sku: "SK-009",
    name: "Skincare Gift Set",
    category: "Beauty",
    price: 59.99,
    stock: 7,
    status: "Low Stock",
  },
  {
    id: 10,
    sku: "TW-010",
    name: "Towel Set Luxury",
    category: "Home & Kitchen",
    price: 34.99,
    stock: 20,
    status: "In Stock",
  },
  {
    id: 11,
    sku: "MB-011",
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 149.99,
    stock: 3,
    status: "Low Stock",
  },
  {
    id: 12,
    sku: "DU-012",
    name: "Dumbbell Set 20kg",
    category: "Sports & Fitness",
    price: 89.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 13,
    sku: "FP-013",
    name: "Face Moisturizer SPF50",
    category: "Beauty",
    price: 29.99,
    stock: 52,
    status: "Trending",
  },
  {
    id: 14,
    sku: "AR-014",
    name: "Air Purifier HEPA",
    category: "Home & Kitchen",
    price: 179.99,
    stock: 14,
    status: "In Stock",
  },
  {
    id: 15,
    sku: "WB-015",
    name: "Water Bottle Insulated",
    category: "Sports & Fitness",
    price: 24.99,
    stock: 88,
    status: "Trending",
  },
  {
    id: 16,
    sku: "SP-016",
    name: "Smartphone Stand 360°",
    category: "Electronics",
    price: 19.99,
    stock: 4,
    status: "Low Stock",
  },
  {
    id: 17,
    sku: "HL-017",
    name: "Hair Dryer Ionic",
    category: "Beauty",
    price: 69.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 18,
    sku: "PL-018",
    name: "Plant Grow Light LED",
    category: "Home & Kitchen",
    price: 44.99,
    stock: 31,
    status: "In Stock",
  },
  {
    id: 19,
    sku: "RF-019",
    name: "Resistance Bands Set",
    category: "Sports & Fitness",
    price: 18.99,
    stock: 6,
    status: "Low Stock",
  },
  {
    id: 20,
    sku: "SS-020",
    name: "Sunscreen SPF100",
    category: "Beauty",
    price: 22.99,
    stock: 75,
    status: "In Stock",
  },
  {
    id: 21,
    sku: "NB-021",
    name: "Noise Cancelling Buds",
    category: "Electronics",
    price: 249.99,
    stock: 29,
    status: "Trending",
  },
  {
    id: 22,
    sku: "CT-022",
    name: "Cast Iron Skillet",
    category: "Home & Kitchen",
    price: 54.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 23,
    sku: "TM-023",
    name: "Treadmill Compact",
    category: "Sports & Fitness",
    price: 499.99,
    stock: 2,
    status: "Low Stock",
  },
  {
    id: 24,
    sku: "LI-024",
    name: "Lip Care Set",
    category: "Beauty",
    price: 16.99,
    stock: 44,
    status: "In Stock",
  },
  {
    id: 25,
    sku: "SL-025",
    name: "Smart LED Strip 5m",
    category: "Electronics",
    price: 34.99,
    stock: 61,
    status: "In Stock",
  },
  {
    id: 26,
    sku: "KN-026",
    name: "Kitchen Knife Set",
    category: "Home & Kitchen",
    price: 119.99,
    stock: 8,
    status: "Low Stock",
  },
  {
    id: 27,
    sku: "JM-027",
    name: "Jump Rope Speed",
    category: "Sports & Fitness",
    price: 14.99,
    stock: 90,
    status: "In Stock",
  },
  {
    id: 28,
    sku: "PS-028",
    name: "Perfume Set Unisex",
    category: "Beauty",
    price: 89.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 29,
    sku: "WC-029",
    name: "Webcam 4K Ultra",
    category: "Electronics",
    price: 109.99,
    stock: 17,
    status: "In Stock",
  },
  {
    id: 30,
    sku: "TV-030",
    name: "Towel Warmer Electric",
    category: "Home & Kitchen",
    price: 64.99,
    stock: 3,
    status: "Low Stock",
  },
  {
    id: 31,
    sku: "CY-031",
    name: "Cycling Gloves Pro",
    category: "Sports & Fitness",
    price: 21.99,
    stock: 33,
    status: "In Stock",
  },
  {
    id: 32,
    sku: "EY-032",
    name: "Eye Cream Anti-Age",
    category: "Beauty",
    price: 49.99,
    stock: 5,
    status: "Low Stock",
  },
  {
    id: 33,
    sku: "SG-033",
    name: "Smart Glasses AR",
    category: "Electronics",
    price: 399.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 34,
    sku: "FN-034",
    name: "Food Processor 10-Cup",
    category: "Home & Kitchen",
    price: 144.99,
    stock: 22,
    status: "Trending",
  },
  {
    id: 35,
    sku: "KT-035",
    name: "Kettlebell 16kg",
    category: "Sports & Fitness",
    price: 59.99,
    stock: 1,
    status: "Low Stock",
  },
  {
    id: 36,
    sku: "BB-036",
    name: "Body Butter Cream",
    category: "Beauty",
    price: 19.99,
    stock: 58,
    status: "In Stock",
  },
  {
    id: 37,
    sku: "HU-037",
    name: "Humidifier Ultrasonic",
    category: "Home & Kitchen",
    price: 54.99,
    stock: 11,
    status: "In Stock",
  },
  {
    id: 38,
    sku: "PM-038",
    name: "Power Bank 20000mAh",
    category: "Electronics",
    price: 44.99,
    stock: 40,
    status: "Trending",
  },
  {
    id: 39,
    sku: "YG-039",
    name: "Yoga Block Set",
    category: "Sports & Fitness",
    price: 17.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 40,
    sku: "SC-040",
    name: "Scalp Serum Growth",
    category: "Beauty",
    price: 37.99,
    stock: 9,
    status: "Low Stock",
  },
  {
    id: 41,
    sku: "GC-041",
    name: "Gaming Chair Ergonomic",
    category: "Electronics",
    price: 349.99,
    stock: 6,
    status: "Low Stock",
  },
  {
    id: 42,
    sku: "DW-042",
    name: "Dish Washer Tablets 60pk",
    category: "Home & Kitchen",
    price: 12.99,
    stock: 200,
    status: "In Stock",
  },
  {
    id: 43,
    sku: "PR-043",
    name: "Protein Shaker 700ml",
    category: "Sports & Fitness",
    price: 11.99,
    stock: 77,
    status: "In Stock",
  },
  {
    id: 44,
    sku: "NC-044",
    name: "Nail Care Kit Professional",
    category: "Beauty",
    price: 28.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 45,
    sku: "MS-045",
    name: "Monitor Stand Dual",
    category: "Electronics",
    price: 79.99,
    stock: 25,
    status: "In Stock",
  },
  {
    id: 46,
    sku: "RG-046",
    name: "Rug Non-Slip 160x230",
    category: "Home & Kitchen",
    price: 99.99,
    stock: 4,
    status: "Low Stock",
  },
  {
    id: 47,
    sku: "SW-047",
    name: "Swimming Goggles Anti-Fog",
    category: "Sports & Fitness",
    price: 16.99,
    stock: 55,
    status: "Trending",
  },
  {
    id: 48,
    sku: "SH-048",
    name: "Sheet Mask Variety 20pk",
    category: "Beauty",
    price: 24.99,
    stock: 83,
    status: "Trending",
  },
  {
    id: 49,
    sku: "TB-049",
    name: "Tablet Stand Foldable",
    category: "Electronics",
    price: 27.99,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: 50,
    sku: "CK-050",
    name: "Candle Set Aromatherapy",
    category: "Home & Kitchen",
    price: 42.99,
    stock: 16,
    status: "In Stock",
  },
];

export const CATEGORIES = [
  "All Categories",
  "Electronics",
  "Home & Kitchen",
  "Sports & Fitness",
  "Beauty",
];

export const STATUSES = [
  "All Statuses",
  "In Stock",
  "Out of Stock",
  "Low Stock",
  "Trending",
];

export const PAGE_SIZE = 5;

export const statusConfig = {
  "In Stock": {
    bg: "bg-green-100",
    text: "text-green-700",
    icon: <HiTrendingUp size={13} />,
  },
  Trending: {
    bg: "bg-green-100",
    text: "text-green-700",
    icon: <HiTrendingUp size={13} />,
  },
  "Out of Stock": {
    bg: "bg-red-100",
    text: "text-red-600",
    icon: <TbPackageOff size={13} />,
  },
  "Low Stock": {
    bg: "bg-amber-100",
    text: "text-amber-600",
    icon: <TbAlertTriangleFilled size={13} />,
  },
};
