
const LOGO_TOKEN = import.meta.env.VITE_LOGO_API_KEY;

const logo = (domain) => `https://img.logo.dev/${domain}?token=${LOGO_TOKEN}`;

export const ALL_BRANDS = [
  {
    id: 1,
    name: "Apple",
    logo: logo("apple.com"),
    description: "Consumer electronics, smartphones, laptops and accessories",
    products: 312,
    status: "Active",
    addedOn: "May 20, 2025",
  },
  {
    id: 2,
    name: "Samsung",
    logo: logo("samsung.com"),
    description: "Smartphones, tablets, home appliances and electronics",
    products: 278,
    status: "Active",
    addedOn: "May 18, 2025",
  },
  {
    id: 3,
    name: "Nike",
    logo: logo("nike.com"),
    description: "Sportswear, shoes, and fitness accessories",
    products: 456,
    status: "Active",
    addedOn: "May 15, 2025",
  },
  {
    id: 4,
    name: "Adidas",
    logo: logo("adidas.com"),
    description: "Athletic wear, footwear and sports accessories",
    products: 398,
    status: "Active",
    addedOn: "May 12, 2025",
  },
  {
    id: 5,
    name: "Sony",
    logo: logo("sony.com"),
    description: "Electronics, gaming, entertainment and accessories",
    products: 189,
    status: "Active",
    addedOn: "May 10, 2025",
  },
  {
    id: 6,
    name: "JBL",
    logo: logo("jbl.com"),
    description: "Audio equipment, speakers and headphones",
    products: 156,
    status: "Inactive",
    addedOn: "May 8, 2025",
  },
  {
    id: 7,
    name: "boAt",
    logo: logo("boat-lifestyle.com"),
    description: "Audio products, wearables and mobile accessories",
    products: 245,
    status: "Active",
    addedOn: "May 5, 2025",
  },
  {
    id: 8,
    name: "Dell",
    logo: logo("dell.com"),
    description: "Laptops, desktops and computer accessories",
    products: 211,
    status: "Active",
    addedOn: "May 3, 2025",
  },
  {
    id: 9,
    name: "HP",
    logo: logo("hp.com"),
    description: "Printers, laptops and computing hardware",
    products: 178,
    status: "Active",
    addedOn: "Apr 30, 2025",
  },
  {
    id: 10,
    name: "Lenovo",
    logo: logo("lenovo.com"),
    description: "Laptops, tablets and workstation accessories",
    products: 203,
    status: "Active",
    addedOn: "Apr 28, 2025",
  },
  {
    id: 11,
    name: "Asus",
    logo: logo("asus.com"),
    description: "Gaming laptops, monitors and motherboards",
    products: 167,
    status: "Active",
    addedOn: "Apr 25, 2025",
  },
  {
    id: 12,
    name: "Acer",
    logo: logo("acer.com"),
    description: "Budget laptops, monitors and peripherals",
    products: 144,
    status: "Active",
    addedOn: "Apr 22, 2025",
  },
  {
    id: 13,
    name: "MSI",
    logo: logo("msi.com"),
    description: "Gaming PCs, laptops and graphics cards",
    products: 132,
    status: "Active",
    addedOn: "Apr 20, 2025",
  },
  {
    id: 14,
    name: "LG",
    logo: logo("lg.com"),
    description: "TVs, home appliances and displays",
    products: 291,
    status: "Active",
    addedOn: "Apr 18, 2025",
  },
  {
    id: 15,
    name: "Philips",
    logo: logo("philips.com"),
    description: "Healthcare, lighting and consumer electronics",
    products: 185,
    status: "Active",
    addedOn: "Apr 15, 2025",
  },
  {
    id: 16,
    name: "Bose",
    logo: logo("bose.com"),
    description: "Premium audio equipment and noise-cancelling headphones",
    products: 98,
    status: "Active",
    addedOn: "Apr 12, 2025",
  },
  {
    id: 17,
    name: "Sennheiser",
    logo: logo("sennheiser.com"),
    description: "Professional audio, microphones and headphones",
    products: 87,
    status: "Active",
    addedOn: "Apr 10, 2025",
  },
  {
    id: 18,
    name: "Canon",
    logo: logo("canon.com"),
    description: "Cameras, printers and imaging accessories",
    products: 213,
    status: "Active",
    addedOn: "Apr 8, 2025",
  },
  {
    id: 19,
    name: "Nikon",
    logo: logo("nikonusa.com"),
    description: "DSLR and mirrorless cameras and lenses",
    products: 176,
    status: "Inactive",
    addedOn: "Apr 5, 2025",
  },
  {
    id: 20,
    name: "GoPro",
    logo: logo("gopro.com"),
    description: "Action cameras and accessories",
    products: 64,
    status: "Active",
    addedOn: "Apr 3, 2025",
  },
  {
    id: 21,
    name: "DJI",
    logo: logo("dji.com"),
    description: "Drones, gimbals and aerial imaging equipment",
    products: 92,
    status: "Active",
    addedOn: "Apr 1, 2025",
  },
  {
    id: 22,
    name: "Xiaomi",
    logo: logo("xiaomi.com"),
    description: "Smartphones, smart home and wearables",
    products: 334,
    status: "Active",
    addedOn: "Mar 28, 2025",
  },
  {
    id: 23,
    name: "OnePlus",
    logo: logo("oneplus.com"),
    description: "Flagship smartphones and audio accessories",
    products: 121,
    status: "Active",
    addedOn: "Mar 25, 2025",
  },
  {
    id: 24,
    name: "Realme",
    logo: logo("realme.com"),
    description: "Budget smartphones and accessories",
    products: 145,
    status: "Active",
    addedOn: "Mar 22, 2025",
  },
  {
    id: 25,
    name: "Vivo",
    logo: logo("vivo.com"),
    description: "Smartphones and mobile accessories",
    products: 138,
    status: "Inactive",
    addedOn: "Mar 20, 2025",
  },
  {
    id: 26,
    name: "Oppo",
    logo: logo("oppo.com"),
    description: "Smartphones, audio and smart accessories",
    products: 152,
    status: "Active",
    addedOn: "Mar 18, 2025",
  },
  {
    id: 27,
    name: "Motorola",
    logo: logo("motorola.com"),
    description: "Mid-range smartphones and accessories",
    products: 119,
    status: "Active",
    addedOn: "Mar 15, 2025",
  },
  {
    id: 28,
    name: "Nokia",
    logo: logo("nokia.com"),
    description: "Smartphones and telecommunications equipment",
    products: 96,
    status: "Inactive",
    addedOn: "Mar 12, 2025",
  },
  {
    id: 29,
    name: "Puma",
    logo: logo("puma.com"),
    description: "Sportswear, footwear and sports accessories",
    products: 287,
    status: "Active",
    addedOn: "Mar 10, 2025",
  },
  {
    id: 30,
    name: "Reebok",
    logo: logo("reebok.com"),
    description: "Athletic footwear and fitness apparel",
    products: 214,
    status: "Active",
    addedOn: "Mar 8, 2025",
  },
  {
    id: 31,
    name: "Under Armour",
    logo: logo("underarmour.com.au"),
    description: "Performance sportswear and athletic gear",
    products: 198,
    status: "Active",
    addedOn: "Mar 5, 2025",
  },
  {
    id: 32,
    name: "New Balance",
    logo: logo("newbalance.com"),
    description: "Running shoes and athletic apparel",
    products: 176,
    status: "Active",
    addedOn: "Mar 3, 2025",
  },
  {
    id: 33,
    name: "Skullcandy",
    logo: logo("skullcandy.com"),
    description: "Budget headphones and audio accessories",
    products: 67,
    status: "Active",
    addedOn: "Mar 1, 2025",
  },
  {
    id: 34,
    name: "Razer",
    logo: logo("razer.com"),
    description: "Gaming peripherals, laptops and accessories",
    products: 143,
    status: "Active",
    addedOn: "Feb 26, 2025",
  },
  {
    id: 35,
    name: "Logitech",
    logo: logo("logitech.com"),
    description: "Mice, keyboards, webcams and audio peripherals",
    products: 221,
    status: "Active",
    addedOn: "Feb 24, 2025",
  },
  {
    id: 36,
    name: "Corsair",
    logo: logo("corsair.com"),
    description: "Gaming peripherals and PC components",
    products: 167,
    status: "Active",
    addedOn: "Feb 22, 2025",
  },
  {
    id: 37,
    name: "SteelSeries",
    logo: logo("steelseries.com"),
    description: "Gaming headsets, mice and keyboards",
    products: 112,
    status: "Active",
    addedOn: "Feb 20, 2025",
  },
  {
    id: 38,
    name: "HyperX",
    logo: logo("hyperx.com"),
    description: "Gaming peripherals and memory solutions",
    products: 134,
    status: "Inactive",
    addedOn: "Feb 18, 2025",
  },
  {
    id: 39,
    name: "Intel",
    logo: logo("intel.com"),
    description: "Processors, GPUs and computing hardware",
    products: 89,
    status: "Active",
    addedOn: "Feb 15, 2025",
  },
  {
    id: 40,
    name: "AMD",
    logo: logo("amd.com"),
    description: "Processors and graphics cards",
    products: 76,
    status: "Active",
    addedOn: "Feb 12, 2025",
  },
  {
    id: 41,
    name: "Nvidia",
    logo: logo("nvidia.com"),
    description: "Graphics cards and AI computing hardware",
    products: 68,
    status: "Active",
    addedOn: "Feb 10, 2025",
  },
  {
    id: 42,
    name: "Western Digital",
    logo: logo("westerndigital.com"),
    description: "Hard drives, SSDs and storage solutions",
    products: 121,
    status: "Active",
    addedOn: "Feb 8, 2025",
  },
  {
    id: 43,
    name: "Seagate",
    logo: logo("seagate.com"),
    description: "HDDs and cloud storage solutions",
    products: 98,
    status: "Active",
    addedOn: "Feb 5, 2025",
  },
  {
    id: 44,
    name: "Kingston",
    logo: logo("kingston.com"),
    description: "RAM, SSDs and flash storage",
    products: 87,
    status: "Active",
    addedOn: "Feb 3, 2025",
  },
  {
    id: 45,
    name: "Crucial",
    logo: logo("crucial.com"),
    description: "Memory and storage upgrades",
    products: 74,
    status: "Inactive",
    addedOn: "Feb 1, 2025",
  },
  {
    id: 46,
    name: "TP-Link",
    logo: logo("tp-link.com"),
    description: "Networking equipment, routers and smart home",
    products: 163,
    status: "Active",
    addedOn: "Jan 28, 2025",
  },
  {
    id: 47,
    name: "Netgear",
    logo: logo("netgear.com"),
    description: "Routers, modems and networking solutions",
    products: 112,
    status: "Active",
    addedOn: "Jan 25, 2025",
  },
  {
    id: 48,
    name: "D-Link",
    logo: logo("dlink.com"),
    description: "Networking hardware and smart home devices",
    products: 98,
    status: "Inactive",
    addedOn: "Jan 22, 2025",
  },
  {
    id: 49,
    name: "Belkin",
    logo: logo("belkin.com"),
    description: "Cables, chargers and mobile accessories",
    products: 145,
    status: "Active",
    addedOn: "Jan 20, 2025",
  },
  {
    id: 50,
    name: "Anker",
    logo: logo("anker.com"),
    description: "Chargers, power banks and audio products",
    products: 189,
    status: "Active",
    addedOn: "Jan 18, 2025",
  },
  {
    id: 51,
    name: "Ugreen",
    logo: logo("ugreen.com"),
    description: "Cables, hubs and charging accessories",
    products: 134,
    status: "Active",
    addedOn: "Jan 15, 2025",
  },
  {
    id: 52,
    name: "Baseus",
    logo: logo("baseus.com"),
    description: "Mobile accessories and charging solutions",
    products: 121,
    status: "Active",
    addedOn: "Jan 12, 2025",
  },
  {
    id: 53,
    name: "Microsoft",
    logo: logo("microsoft.com"),
    description: "Software, Surface devices and peripherals",
    products: 267,
    status: "Active",
    addedOn: "Jan 10, 2025",
  },
  {
    id: 54,
    name: "Google",
    logo: logo("google.com"),
    description: "Pixel phones, Nest smart home and accessories",
    products: 198,
    status: "Active",
    addedOn: "Jan 8, 2025",
  },
  {
    id: 55,
    name: "Amazon",
    logo: logo("amazon.com"),
    description: "Echo, Kindle and Fire smart devices",
    products: 176,
    status: "Active",
    addedOn: "Jan 5, 2025",
  },
  {
    id: 56,
    name: "Fitbit",
    logo: logo("fitbit.com"),
    description: "Fitness trackers and smartwatches",
    products: 87,
    status: "Inactive",
    addedOn: "Jan 3, 2025",
  },
  {
    id: 57,
    name: "Garmin",
    logo: logo("garmin.com"),
    description: "GPS devices, smartwatches and fitness trackers",
    products: 143,
    status: "Active",
    addedOn: "Jan 1, 2025",
  },
  {
    id: 58,
    name: "Amazfit",
    logo: logo("amazfit.com"),
    description: "Budget smartwatches and fitness bands",
    products: 96,
    status: "Active",
    addedOn: "Dec 28, 2024",
  },
  {
    id: 59,
    name: "Fossil",
    logo: logo("fossil.com"),
    description: "Hybrid and traditional smartwatches",
    products: 112,
    status: "Active",
    addedOn: "Dec 25, 2024",
  },
  {
    id: 60,
    name: "Whirlpool",
    logo: logo("whirlpool.com"),
    description: "Home appliances and kitchen equipment",
    products: 198,
    status: "Active",
    addedOn: "Dec 22, 2024",
  },
  {
    id: 61,
    name: "Bosch",
    logo: logo("bosch.com"),
    description: "Home appliances, power tools and automotive",
    products: 234,
    status: "Active",
    addedOn: "Dec 20, 2024",
  },
  {
    id: 62,
    name: "Haier",
    logo: logo("haier.com"),
    description: "Refrigerators, washing machines and ACs",
    products: 167,
    status: "Active",
    addedOn: "Dec 18, 2024",
  },
  {
    id: 63,
    name: "Voltas",
    logo: logo("voltas.com"),
    description: "Air conditioners and home appliances",
    products: 145,
    status: "Active",
    addedOn: "Dec 15, 2024",
  },
  {
    id: 64,
    name: "Godrej",
    logo: logo("godrej.com"),
    description: "Refrigerators, furniture and consumer goods",
    products: 189,
    status: "Inactive",
    addedOn: "Dec 12, 2024",
  },
  {
    id: 65,
    name: "Blue Star",
    logo: logo("bluestarindia.com"),
    description: "Air conditioners and commercial cooling",
    products: 112,
    status: "Active",
    addedOn: "Dec 10, 2024",
  },
  {
    id: 66,
    name: "Panasonic",
    logo: logo("panasonic.com"),
    description: "Electronics, cameras and home appliances",
    products: 221,
    status: "Active",
    addedOn: "Dec 8, 2024",
  },
  {
    id: 67,
    name: "Sharp",
    logo: logo("sharp.com"),
    description: "TVs, microwaves and home electronics",
    products: 156,
    status: "Active",
    addedOn: "Dec 5, 2024",
  },
  {
    id: 68,
    name: "Toshiba",
    logo: logo("toshiba.com"),
    description: "Storage, TVs and industrial electronics",
    products: 132,
    status: "Inactive",
    addedOn: "Dec 3, 2024",
  },
  {
    id: 69,
    name: "TCL",
    logo: logo("tcl.com"),
    description: "Budget TVs and smart home devices",
    products: 167,
    status: "Active",
    addedOn: "Dec 1, 2024",
  },
  {
    id: 70,
    name: "Hisense",
    logo: logo("hisense.com"),
    description: "TVs, refrigerators and air conditioners",
    products: 143,
    status: "Active",
    addedOn: "Nov 28, 2024",
  },
  {
    id: 71,
    name: "Dyson",
    logo: logo("dyson.com"),
    description: "Vacuum cleaners, hair care and fans",
    products: 98,
    status: "Active",
    addedOn: "Nov 25, 2024",
  },
  {
    id: 72,
    name: "iRobot",
    logo: logo("irobot.com"),
    description: "Robot vacuums and smart cleaning devices",
    products: 54,
    status: "Active",
    addedOn: "Nov 22, 2024",
  },
  {
    id: 73,
    name: "Eureka Forbes",
    logo: logo("eurekaforbes.com"),
    description: "Vacuum cleaners and water purifiers",
    products: 87,
    status: "Active",
    addedOn: "Nov 20, 2024",
  },
  {
    id: 74,
    name: "Kent",
    logo: logo("kent.co.in"),
    description: "Water purifiers and health appliances",
    products: 76,
    status: "Active",
    addedOn: "Nov 18, 2024",
  },
  {
    id: 75,
    name: "Havells",
    logo: logo("havells.com"),
    description: "Electrical equipment, fans and lighting",
    products: 198,
    status: "Active",
    addedOn: "Nov 15, 2024",
  },
  {
    id: 76,
    name: "Orient",
    logo: logo("orientelectric.com"),
    description: "Fans, lighting and home appliances",
    products: 145,
    status: "Inactive",
    addedOn: "Nov 12, 2024",
  },
  {
    id: 77,
    name: "Bajaj",
    logo: logo("bajajelectricals.com"),
    description: "Fans, lighting and small kitchen appliances",
    products: 167,
    status: "Active",
    addedOn: "Nov 10, 2024",
  },
  {
    id: 78,
    name: "Prestige",
    logo: logo("ttkprestige.com"),
    description: "Cookware, pressure cookers and kitchen appliances",
    products: 189,
    status: "Active",
    addedOn: "Nov 8, 2024",
  },
  {
    id: 79,
    name: "Philips Hue",
    logo: logo("philips.com"),
    description: "Smart lighting and home automation",
    products: 87,
    status: "Active",
    addedOn: "Nov 5, 2024",
  },
  {
    id: 80,
    name: "Syska",
    logo: logo("syska.co.in"),
    description: "LED lights, mobile accessories and fans",
    products: 134,
    status: "Active",
    addedOn: "Nov 3, 2024",
  },
  {
    id: 81,
    name: "Noise",
    logo: logo("gonoise.com"),
    description: "Budget smartwatches, earbuds and fitness bands",
    products: 112,
    status: "Active",
    addedOn: "Nov 1, 2024",
  },
  {
    id: 82,
    name: "Fire-Boltt",
    logo: logo("fireboltt.com"),
    description: "Smartwatches and fitness trackers",
    products: 98,
    status: "Active",
    addedOn: "Oct 28, 2024",
  },
  {
    id: 83,
    name: "Zebronics",
    logo: logo("zebronics.com"),
    description: "Budget peripherals, speakers and accessories",
    products: 143,
    status: "Inactive",
    addedOn: "Oct 25, 2024",
  },
  {
    id: 84,
    name: "Portronics",
    logo: logo("portronics.com"),
    description: "Wireless audio, chargers and tech accessories",
    products: 121,
    status: "Active",
    addedOn: "Oct 22, 2024",
  },
  {
    id: 85,
    name: "Ambrane",
    logo: logo("ambraneindia.com"),
    description: "Power banks, cables and wireless audio",
    products: 96,
    status: "Active",
    addedOn: "Oct 20, 2024",
  },
  {
    id: 86,
    name: "Intex",
    logo: logo("intex.in"),
    description: "Budget smartphones, speakers and accessories",
    products: 112,
    status: "Inactive",
    addedOn: "Oct 18, 2024",
  },
];

export const ITEMS_PER_PAGE = 8;

export const STATUS_OPTIONS = ["All Status", "Active", "Inactive"];

export const SORT_OPTIONS = [
  "Sort by: Recently Added",
  "Sort by: Name (A–Z)",
  "Sort by: Name (Z–A)",
  "Sort by: Most Products",
];
