import { GoClock } from "react-icons/go";
import {
  IoCheckmarkCircleOutline,
  IoCloseCircleOutline,
} from "react-icons/io5";
import { TbTruckDelivery } from "react-icons/tb";
import { MdPendingActions } from "react-icons/md";

export const DUMMY_ORDERS = [
  {
    id: "#ORD-000248",
    customer: "Michael Scott",
    email: "michael.scott@example.com",
    initials: "MS",
    color: "bg-violet-200 text-violet-700",
    date: "May 20, 2024",
    time: "10:30 AM",
    total: "$299.98",
    payment: "Credit Card",
    cardLast4: "4242",
    paymentIcon: "mastercard",
    status: "Delivered",
    items: 3,
  },
  {
    id: "#ORD-000247",
    customer: "Jim Halpert",
    email: "jim.halpert@example.com",
    initials: "JB",
    color: "bg-blue-200 text-blue-700",
    date: "May 20, 2024",
    time: "09:15 AM",
    total: "$159.97",
    payment: "Credit Card",
    cardLast4: "1111",
    paymentIcon: "visa",
    status: "Processing",
    items: 2,
  },
  {
    id: "#ORD-000246",
    customer: "Pam Beesly",
    email: "pam.beesly@example.com",
    initials: "PW",
    color: "bg-green-200 text-green-700",
    date: "May 19, 2024",
    time: "04:45 PM",
    total: "$89.99",
    payment: "PayPal",
    cardLast4: null,
    paymentIcon: "paypal",
    status: "Shipped",
    items: 1,
  },
  {
    id: "#ORD-000245",
    customer: "Dwight Schrute",
    email: "dwight.schrute@example.com",
    initials: "DW",
    color: "bg-yellow-200 text-yellow-700",
    date: "May 19, 2024",
    time: "11:20 AM",
    total: "$399.99",
    payment: "Credit Card",
    cardLast4: "5555",
    paymentIcon: "visa",
    status: "Pending",
    items: 4,
  },
  {
    id: "#ORD-000244",
    customer: "Angela Martin",
    email: "angela.martin@example.com",
    initials: "AH",
    color: "bg-pink-200 text-pink-700",
    date: "May 18, 2024",
    time: "03:30 PM",
    total: "$29.99",
    payment: "Credit Card",
    cardLast4: "8888",
    paymentIcon: "mastercard",
    status: "Cancelled",
    items: 1,
  },
  {
    id: "#ORD-000243",
    customer: "Ryan Howard",
    email: "ryan.howard@example.com",
    initials: "RH",
    color: "bg-orange-200 text-orange-700",
    date: "May 18, 2024",
    time: "01:10 PM",
    total: "$549.00",
    payment: "Credit Card",
    cardLast4: "3210",
    paymentIcon: "visa",
    status: "Delivered",
    items: 5,
  },
  {
    id: "#ORD-000242",
    customer: "Kelly Kapoor",
    email: "kelly.kapoor@example.com",
    initials: "KK",
    color: "bg-red-200 text-red-700",
    date: "May 17, 2024",
    time: "02:00 PM",
    total: "$74.50",
    payment: "PayPal",
    cardLast4: null,
    paymentIcon: "paypal",
    status: "Shipped",
    items: 2,
  },
  {
    id: "#ORD-000241",
    customer: "Stanley Hudson",
    email: "stanley.hudson@example.com",
    initials: "SH",
    color: "bg-teal-200 text-teal-700",
    date: "May 17, 2024",
    time: "10:00 AM",
    total: "$199.99",
    payment: "Credit Card",
    cardLast4: "7777",
    paymentIcon: "mastercard",
    status: "Processing",
    items: 3,
  },
  {
    id: "#ORD-000240",
    customer: "Kevin Malone",
    email: "kevin.malone@example.com",
    initials: "KM",
    color: "bg-indigo-200 text-indigo-700",
    date: "May 16, 2024",
    time: "09:45 AM",
    total: "$89.00",
    payment: "Credit Card",
    cardLast4: "1234",
    paymentIcon: "visa",
    status: "Delivered",
    items: 1,
  },
  {
    id: "#ORD-000239",
    customer: "Oscar Martinez",
    email: "oscar.martinez@example.com",
    initials: "OM",
    color: "bg-cyan-200 text-cyan-700",
    date: "May 16, 2024",
    time: "11:30 AM",
    total: "$349.75",
    payment: "PayPal",
    cardLast4: null,
    paymentIcon: "paypal",
    status: "Pending",
    items: 4,
  },
  {
    id: "#ORD-000238",
    customer: "Meredith Palmer",
    email: "meredith.palmer@example.com",
    initials: "MP",
    color: "bg-purple-200 text-purple-700",
    date: "May 15, 2024",
    time: "03:00 PM",
    total: "$120.00",
    payment: "Credit Card",
    cardLast4: "9876",
    paymentIcon: "mastercard",
    status: "Cancelled",
    items: 2,
  },
  {
    id: "#ORD-000237",
    customer: "Creed Bratton",
    email: "creed.bratton@example.com",
    initials: "CB",
    color: "bg-lime-200 text-lime-700",
    date: "May 15, 2024",
    time: "08:15 AM",
    total: "$67.49",
    payment: "Credit Card",
    cardLast4: "4321",
    paymentIcon: "visa",
    status: "Shipped",
    items: 1,
  },
  {
    id: "#ORD-000236",
    customer: "Toby Flenderson",
    email: "toby.flenderson@example.com",
    initials: "TF",
    color: "bg-slate-200 text-slate-700",
    date: "May 14, 2024",
    time: "04:00 PM",
    total: "$215.00",
    payment: "PayPal",
    cardLast4: null,
    paymentIcon: "paypal",
    status: "Delivered",
    items: 3,
  },
  {
    id: "#ORD-000235",
    customer: "Darryl Philbin",
    email: "darryl.philbin@example.com",
    initials: "DP",
    color: "bg-amber-200 text-amber-700",
    date: "May 14, 2024",
    time: "12:30 PM",
    total: "$499.99",
    payment: "Credit Card",
    cardLast4: "6543",
    paymentIcon: "mastercard",
    status: "Processing",
    items: 6,
  },
  {
    id: "#ORD-000234",
    customer: "Phyllis Vance",
    email: "phyllis.vance@example.com",
    initials: "PV",
    color: "bg-rose-200 text-rose-700",
    date: "May 13, 2024",
    time: "02:45 PM",
    total: "$38.99",
    payment: "Credit Card",
    cardLast4: "2345",
    paymentIcon: "visa",
    status: "Delivered",
    items: 1,
  },
  {
    id: "#ORD-000233",
    customer: "Jan Levinson",
    email: "jan.levinson@example.com",
    initials: "JL",
    color: "bg-fuchsia-200 text-fuchsia-700",
    date: "May 13, 2024",
    time: "10:20 AM",
    total: "$789.50",
    payment: "Credit Card",
    cardLast4: "8765",
    paymentIcon: "mastercard",
    status: "Shipped",
    items: 7,
  },
  {
    id: "#ORD-000232",
    customer: "David Wallace",
    email: "david.wallace@example.com",
    initials: "DW",
    color: "bg-emerald-200 text-emerald-700",
    date: "May 12, 2024",
    time: "09:00 AM",
    total: "$1,200.00",
    payment: "Credit Card",
    cardLast4: "1357",
    paymentIcon: "visa",
    status: "Delivered",
    items: 10,
  },
  {
    id: "#ORD-000231",
    customer: "Roy Anderson",
    email: "roy.anderson@example.com",
    initials: "RA",
    color: "bg-sky-200 text-sky-700",
    date: "May 12, 2024",
    time: "11:00 AM",
    total: "$55.00",
    payment: "PayPal",
    cardLast4: null,
    paymentIcon: "paypal",
    status: "Cancelled",
    items: 1,
  },
  {
    id: "#ORD-000230",
    customer: "Todd Packer",
    email: "todd.packer@example.com",
    initials: "TP",
    color: "bg-orange-200 text-orange-700",
    date: "May 11, 2024",
    time: "01:30 PM",
    total: "$320.00",
    payment: "Credit Card",
    cardLast4: "2468",
    paymentIcon: "mastercard",
    status: "Pending",
    items: 3,
  },
  {
    id: "#ORD-000229",
    customer: "Charles Miner",
    email: "charles.miner@example.com",
    initials: "CM",
    color: "bg-violet-200 text-violet-700",
    date: "May 11, 2024",
    time: "03:15 PM",
    total: "$175.25",
    payment: "Credit Card",
    cardLast4: "3579",
    paymentIcon: "visa",
    status: "Processing",
    items: 2,
  },
];

export const ORDERS_PER_PAGE = 5;

export const STATUS_OPTIONS = [
  "All Statuses",
  "Delivered",
  "Processing",
  "Shipped",
  "Pending",
  "Cancelled",
];

export const PAYMENT_OPTIONS = ["All Payment Methods", "Credit Card", "PayPal"];

export const STATUS_CONFIG = {
  Delivered: {
    bg: "bg-green-50",
    text: "text-green-700",
    border: "border-green-200",
    Icon: IoCheckmarkCircleOutline,
  },
  Processing: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    Icon: GoClock,
  },
  Shipped: {
    bg: "bg-indigo-50",
    text: "text-indigo-700",
    border: "border-indigo-200",
    Icon: TbTruckDelivery,
  },
  Pending: {
    bg: "bg-orange-50",
    text: "text-orange-700",
    border: "border-orange-200",
    Icon: MdPendingActions,
  },
  Cancelled: {
    bg: "bg-red-50",
    text: "text-red-700",
    border: "border-red-200",
    Icon: IoCloseCircleOutline,
  },
};
