
export const ALL_COUPONS = [
  {
    id: 1,
    code: "WELCOME10",
    description: "Welcome discount for new customers",
    discount: "10% OFF",
    type: "Percentage",
    minPurchase: 50,
    usageLimit: 500,
    redeemed: 245,
    validTill: "Jun 15, 2026",
    status: "Active",
  },
  {
    id: 2,
    code: "SUMMER20",
    description: "Summer special offer",
    discount: "20% OFF",
    type: "Percentage",
    minPurchase: 100,
    usageLimit: 1000,
    redeemed: 632,
    validTill: "Jul 31, 2026",
    status: "Active",
  },
  {
    id: 3,
    code: "FLAT100",
    description: "Flat $100 off on orders above $499",
    discount: "$100 OFF",
    type: "Fixed Amount",
    minPurchase: 499,
    usageLimit: 300,
    redeemed: 89,
    validTill: "Jun 30, 2026",
    status: "Active",
  },
  {
    id: 4,
    code: "FREESHIP",
    description: "Free shipping on all orders",
    discount: "Free Shipping",
    type: "Shipping",
    minPurchase: 0,
    usageLimit: null,
    redeemed: 1245,
    validTill: "May 31, 2026",
    status: "Active",
  },
  {
    id: 5,
    code: "MEGA50",
    description: "Mega sale – 50% off",
    discount: "50% OFF",
    type: "Percentage",
    minPurchase: 200,
    usageLimit: 200,
    redeemed: 200,
    validTill: "May 20, 2025",
    status: "Expired",
  },
  {
    id: 6,
    code: "DIWALI25",
    description: "Diwali Special Offer",
    discount: "25% OFF",
    type: "Percentage",
    minPurchase: 150,
    usageLimit: 1000,
    redeemed: 0,
    validTill: "Oct 31, 2026",
    status: "Scheduled",
  },
  {
    id: 7,
    code: "FLASH15",
    description: "Flash sale – limited time",
    discount: "15% OFF",
    type: "Percentage",
    minPurchase: 75,
    usageLimit: 150,
    redeemed: 98,
    validTill: "Jul 10, 2026",
    status: "Active",
  },
  {
    id: 8,
    code: "NEWUSER30",
    description: "30% off for first-time buyers",
    discount: "30% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: 800,
    redeemed: 431,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 9,
    code: "SHIP50",
    description: "50% off shipping fees",
    discount: "50% OFF",
    type: "Shipping",
    minPurchase: 25,
    usageLimit: 600,
    redeemed: 310,
    validTill: "Aug 15, 2026",
    status: "Active",
  },
  {
    id: 10,
    code: "FLAT200",
    description: "Flat $200 off orders above $999",
    discount: "$200 OFF",
    type: "Fixed Amount",
    minPurchase: 999,
    usageLimit: 100,
    redeemed: 44,
    validTill: "Sep 01, 2026",
    status: "Active",
  },
  {
    id: 11,
    code: "HOLI40",
    description: "Holi festival sale",
    discount: "40% OFF",
    type: "Percentage",
    minPurchase: 120,
    usageLimit: 500,
    redeemed: 500,
    validTill: "Mar 25, 2025",
    status: "Expired",
  },
  {
    id: 12,
    code: "BLACKFRI",
    description: "Black Friday mega deal",
    discount: "60% OFF",
    type: "Percentage",
    minPurchase: 300,
    usageLimit: 2000,
    redeemed: 1876,
    validTill: "Nov 30, 2025",
    status: "Expired",
  },
  {
    id: 13,
    code: "CYBER25",
    description: "Cyber Monday exclusive",
    discount: "25% OFF",
    type: "Percentage",
    minPurchase: 100,
    usageLimit: 1500,
    redeemed: 0,
    validTill: "Dec 02, 2026",
    status: "Scheduled",
  },
  {
    id: 14,
    code: "FREESHIP2",
    description: "Free express shipping",
    discount: "Free Shipping",
    type: "Shipping",
    minPurchase: 150,
    usageLimit: 400,
    redeemed: 123,
    validTill: "Jul 20, 2026",
    status: "Active",
  },
  {
    id: 15,
    code: "LOYALTY10",
    description: "Loyalty reward for returning users",
    discount: "10% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: null,
    redeemed: 2341,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 16,
    code: "FLAT50",
    description: "$50 off on orders above $250",
    discount: "$50 OFF",
    type: "Fixed Amount",
    minPurchase: 250,
    usageLimit: 700,
    redeemed: 289,
    validTill: "Aug 31, 2026",
    status: "Active",
  },
  {
    id: 17,
    code: "XMAS20",
    description: "Christmas holiday special",
    discount: "20% OFF",
    type: "Percentage",
    minPurchase: 80,
    usageLimit: 1200,
    redeemed: 0,
    validTill: "Dec 25, 2026",
    status: "Scheduled",
  },
  {
    id: 18,
    code: "EOFSALE",
    description: "End of season clearance",
    discount: "35% OFF",
    type: "Percentage",
    minPurchase: 60,
    usageLimit: 300,
    redeemed: 300,
    validTill: "Jan 10, 2025",
    status: "Expired",
  },
  {
    id: 19,
    code: "REFER20",
    description: "Referral bonus for inviting friends",
    discount: "20% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: null,
    redeemed: 567,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 20,
    code: "BUNDLE15",
    description: "Bundle purchase discount",
    discount: "15% OFF",
    type: "Percentage",
    minPurchase: 200,
    usageLimit: 250,
    redeemed: 112,
    validTill: "Oct 15, 2026",
    status: "Active",
  },
  {
    id: 21,
    code: "FLAT75",
    description: "$75 flat off above $399",
    discount: "$75 OFF",
    type: "Fixed Amount",
    minPurchase: 399,
    usageLimit: 180,
    redeemed: 67,
    validTill: "Sep 20, 2026",
    status: "Active",
  },
  {
    id: 22,
    code: "PAYDAY",
    description: "Payday weekend sale",
    discount: "12% OFF",
    type: "Percentage",
    minPurchase: 50,
    usageLimit: 600,
    redeemed: 401,
    validTill: "Jun 28, 2026",
    status: "Active",
  },
  {
    id: 23,
    code: "SUPERSAVE",
    description: "Super savings across all categories",
    discount: "45% OFF",
    type: "Percentage",
    minPurchase: 500,
    usageLimit: 100,
    redeemed: 22,
    validTill: "Jul 05, 2026",
    status: "Active",
  },
  {
    id: 24,
    code: "TRYFREE",
    description: "Try a product for free (shipping only)",
    discount: "$0 OFF",
    type: "Fixed Amount",
    minPurchase: 0,
    usageLimit: 50,
    redeemed: 50,
    validTill: "Feb 14, 2025",
    status: "Expired",
  },
  {
    id: 25,
    code: "NEWYEAR",
    description: "New Year countdown deal",
    discount: "30% OFF",
    type: "Percentage",
    minPurchase: 100,
    usageLimit: 900,
    redeemed: 0,
    validTill: "Jan 01, 2027",
    status: "Scheduled",
  },
  {
    id: 26,
    code: "WEEKEND5",
    description: "Weekend-only flat discount",
    discount: "$5 OFF",
    type: "Fixed Amount",
    minPurchase: 30,
    usageLimit: null,
    redeemed: 3412,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 27,
    code: "CLEARANCE",
    description: "Clearance stock discount",
    discount: "70% OFF",
    type: "Percentage",
    minPurchase: 20,
    usageLimit: 200,
    redeemed: 200,
    validTill: "Apr 01, 2025",
    status: "Expired",
  },
  {
    id: 28,
    code: "APP10",
    description: "Download app and get a discount",
    discount: "10% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: null,
    redeemed: 1890,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 29,
    code: "VIPONLY",
    description: "Exclusive VIP member coupon",
    discount: "25% OFF",
    type: "Percentage",
    minPurchase: 200,
    usageLimit: 300,
    redeemed: 189,
    validTill: "Nov 30, 2026",
    status: "Active",
  },
  {
    id: 30,
    code: "SEPT15",
    description: "September savings event",
    discount: "15% OFF",
    type: "Percentage",
    minPurchase: 70,
    usageLimit: 500,
    redeemed: 0,
    validTill: "Sep 30, 2026",
    status: "Scheduled",
  },
  {
    id: 31,
    code: "SHIPS0",
    description: "Zero shipping on orders over $50",
    discount: "Free Shipping",
    type: "Shipping",
    minPurchase: 50,
    usageLimit: null,
    redeemed: 762,
    validTill: "Aug 01, 2026",
    status: "Active",
  },
  {
    id: 32,
    code: "FLAT25",
    description: "$25 off any order",
    discount: "$25 OFF",
    type: "Fixed Amount",
    minPurchase: 25,
    usageLimit: 1000,
    redeemed: 543,
    validTill: "Oct 01, 2026",
    status: "Active",
  },
  {
    id: 33,
    code: "MONSOON",
    description: "Monsoon sale special",
    discount: "22% OFF",
    type: "Percentage",
    minPurchase: 90,
    usageLimit: 400,
    redeemed: 178,
    validTill: "Aug 20, 2026",
    status: "Active",
  },
  {
    id: 34,
    code: "FESTIVE50",
    description: "Festive season mega offer",
    discount: "50% OFF",
    type: "Percentage",
    minPurchase: 300,
    usageLimit: 600,
    redeemed: 0,
    validTill: "Oct 20, 2026",
    status: "Scheduled",
  },
  {
    id: 35,
    code: "THANKYOU",
    description: "Thank you coupon for repeat orders",
    discount: "8% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: null,
    redeemed: 4210,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 36,
    code: "BIGBUY",
    description: "Big purchase reward",
    discount: "$150 OFF",
    type: "Fixed Amount",
    minPurchase: 1500,
    usageLimit: 50,
    redeemed: 12,
    validTill: "Sep 15, 2026",
    status: "Active",
  },
  {
    id: 37,
    code: "TRIAL",
    description: "Trial month promotional code",
    discount: "5% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: 200,
    redeemed: 200,
    validTill: "Mar 01, 2025",
    status: "Expired",
  },
  {
    id: 38,
    code: "EARLYBIRD",
    description: "Early bird purchase discount",
    discount: "18% OFF",
    type: "Percentage",
    minPurchase: 100,
    usageLimit: 350,
    redeemed: 0,
    validTill: "Aug 05, 2026",
    status: "Scheduled",
  },
  {
    id: 39,
    code: "DAILY5",
    description: "Daily deal coupon",
    discount: "$5 OFF",
    type: "Fixed Amount",
    minPurchase: 20,
    usageLimit: null,
    redeemed: 6543,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 40,
    code: "JUMBO40",
    description: "Jumbo size order discount",
    discount: "40% OFF",
    type: "Percentage",
    minPurchase: 400,
    usageLimit: 100,
    redeemed: 34,
    validTill: "Oct 10, 2026",
    status: "Active",
  },
  {
    id: 41,
    code: "SPRINGSALE",
    description: "Spring collection offer",
    discount: "20% OFF",
    type: "Percentage",
    minPurchase: 80,
    usageLimit: 700,
    redeemed: 700,
    validTill: "Apr 30, 2025",
    status: "Expired",
  },
  {
    id: 42,
    code: "FREERETURN",
    description: "Free return shipping coupon",
    discount: "Free Shipping",
    type: "Shipping",
    minPurchase: 0,
    usageLimit: null,
    redeemed: 312,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 43,
    code: "TECH10",
    description: "Electronics category special",
    discount: "10% OFF",
    type: "Percentage",
    minPurchase: 200,
    usageLimit: 500,
    redeemed: 267,
    validTill: "Jul 31, 2026",
    status: "Active",
  },
  {
    id: 44,
    code: "FASHION30",
    description: "Fashion & apparel sale",
    discount: "30% OFF",
    type: "Percentage",
    minPurchase: 100,
    usageLimit: 800,
    redeemed: 0,
    validTill: "Sep 01, 2026",
    status: "Scheduled",
  },
  {
    id: 45,
    code: "SAVE10NOW",
    description: "Instant savings on checkout",
    discount: "$10 OFF",
    type: "Fixed Amount",
    minPurchase: 50,
    usageLimit: 1000,
    redeemed: 891,
    validTill: "Dec 31, 2026",
    status: "Active",
  },
  {
    id: 46,
    code: "PREMIUM20",
    description: "Premium member exclusive offer",
    discount: "20% OFF",
    type: "Percentage",
    minPurchase: 250,
    usageLimit: 200,
    redeemed: 143,
    validTill: "Nov 15, 2026",
    status: "Active",
  },
  {
    id: 47,
    code: "GONE50",
    description: "Going out of stock sale",
    discount: "50% OFF",
    type: "Percentage",
    minPurchase: 0,
    usageLimit: 80,
    redeemed: 80,
    validTill: "May 01, 2025",
    status: "Expired",
  },
  {
    id: 48,
    code: "LAUNCH25",
    description: "New product launch special",
    discount: "25% OFF",
    type: "Percentage",
    minPurchase: 100,
    usageLimit: 400,
    redeemed: 0,
    validTill: "Nov 01, 2026",
    status: "Scheduled",
  },
];

export const ROWS_PER_PAGE = 6;

export const STATUS_OPTIONS = ["All Status", "Active", "Expired", "Scheduled"];

export const TYPE_OPTIONS = ["All Types", "Percentage", "Fixed Amount", "Shipping"];

export const CODE_COLOURS = [
  "bg-violet-100 text-violet-700",
  "bg-emerald-100 text-emerald-700",
  "bg-sky-100 text-sky-700",
  "bg-amber-100 text-amber-700",
  "bg-pink-100 text-pink-700",
  "bg-indigo-100 text-indigo-700",
  "bg-teal-100 text-teal-700",
  "bg-orange-100 text-orange-700",
];

